sonar.projectKey=the-way-to-go-zh-cn
sonar.projectName=the-way-to-go_ZH_CN
sonar.projectVersion=1.0
# 替换成你自己的组织名
sonar.organization=cherleyzhu_the-way-to-go_ZH_CN
sonar.sources=.
sonar.sourceEncoding=UTF-8
