# 项目唯一标识（随便写，英文/数字）
sonar.projectKey=the-way-to-go-zh-cn
# 项目显示名
sonar.projectName=the-way-to-go_ZH_CN
# 版本
sonar.projectVersion=1.0
# 源代码目录：当前根目录（因为你没有 src/main/java）
sonar.sources=.
# 编码
sonar.sourceEncoding=UTF-8
# 语言：让 Sonar 自动识别（支持 Go、Markdown 等）
sonar.language=
